"""added profile pic

Revision ID: 21faf73123e5
Revises: d569348990fc
Create Date: 2023-01-05 10:32:42.728639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21faf73123e5'
down_revision = 'd569348990fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###
