"""upgraded store schema

Revision ID: 4cdb129d8fae
Revises: e8c0a2d1d54d
Create Date: 2023-01-09 17:50:09.445224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdb129d8fae'
down_revision = 'e8c0a2d1d54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
