"""empty message

Revision ID: 4ced99870b1c
Revises: e71b714fcda3
Create Date: 2023-02-06 17:53:23.181634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ced99870b1c'
down_revision = 'e71b714fcda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=False))
        batch_op.drop_constraint('bookshelves_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['owner'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookshelves_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('owner')

    # ### end Alembic commands ###
