"""added store model to database

Revision ID: 517c2f2715f3
Revises: 228320af2a71
Create Date: 2022-12-19 16:24:24.455681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517c2f2715f3'
down_revision = '228320af2a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.String(length=300), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    # ### end Alembic commands ###
