"""changed store schema

Revision ID: 66a2afa51e0c
Revises: 2a0c925c2910
Create Date: 2023-01-07 12:26:46.185693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a2afa51e0c'
down_revision = '2a0c925c2910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('store_bild', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('seats', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('creation_date')
        batch_op.drop_column('seats')
        batch_op.drop_column('store_bild')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
