"""updated bookshelf model

Revision ID: e71b714fcda3
Revises: f1b113451748
Create Date: 2023-01-30 12:28:31.334995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71b714fcda3'
down_revision = 'f1b113451748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbns', sa.JSON(), nullable=True))
        batch_op.drop_column('isbn')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isbn', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('isbns')

    # ### end Alembic commands ###
