"""changed store schema

Revision ID: e8c0a2d1d54d
Revises: 2ff3058bd5e2
Create Date: 2023-01-07 12:29:32.177363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c0a2d1d54d'
down_revision = '2ff3058bd5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('storename', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('store_bild', sa.String(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storename')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stores')
    # ### end Alembic commands ###
