"""deleted book model and updated bookshelf model by isbns

Revision ID: f1b113451748
Revises: 4cdb129d8fae
Create Date: 2023-01-30 11:38:10.502970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b113451748'
down_revision = '4cdb129d8fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschreibung', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookshelves', schema=None) as batch_op:
        batch_op.drop_column('isbn')
        batch_op.drop_column('beschreibung')

    # ### end Alembic commands ###
